// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: shortLink.proto

package server

import (
	"context"

	"shortLink/rpc/internal/logic"
	"shortLink/rpc/internal/svc"
	"shortLink/rpc/pb/shortLink"
)

type ShortLinkServiceServer struct {
	svcCtx *svc.ServiceContext
	shortLink.UnimplementedShortLinkServiceServer
}

func NewShortLinkServiceServer(svcCtx *svc.ServiceContext) *ShortLinkServiceServer {
	return &ShortLinkServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ShortLinkServiceServer) Convert(ctx context.Context, in *shortLink.ConvertRequest) (*shortLink.ConvertResponse, error) {
	l := logic.NewConvertLogic(ctx, s.svcCtx)
	return l.Convert(in)
}

func (s *ShortLinkServiceServer) Search(ctx context.Context, in *shortLink.SearchRequest) (*shortLink.SearchResponse, error) {
	l := logic.NewSearchLogic(ctx, s.svcCtx)
	return l.Search(in)
}
