// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type ConvertRequest struct {
	LongURL string `json:"longURL" validator:"required"`
}

type ConvertResponse struct {
	ShortURL string `json:"shortURL"`
}

type SearchRequest struct {
	ShortURL string `path:"sURL" validator:"required"`
}

type SearchResponse struct {
	LongURL string `json:"longURL"`
}
