// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package handler

import (
	"net/http"

	"shortLink/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/convert",
				Handler: ConvertHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/search/:sURL",
				Handler: SearchHandler(serverCtx),
			},
		},
	)
}
